
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AuthorizationWindow(object):
    def setupUi(self, AuthorizationWindow):
        AuthorizationWindow.setObjectName("AuthorizationWindow")
        AuthorizationWindow.resize(400, 250)
        self.centralwidget = QtWidgets.QWidget(AuthorizationWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_Authorization = QtWidgets.QLabel(self.centralwidget)
        self.label_Authorization.setGeometry(QtCore.QRect(20, 30, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_Authorization.setFont(font)
        self.label_Authorization.setObjectName("label_Authorization")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(50, 90, 291, 71))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_Name = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_Name.setFont(font)
        self.label_Name.setObjectName("label_Name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_Name)
        self.label_Password = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_Password.setFont(font)
        self.label_Password.setObjectName("label_Password")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_Password)
        self.lineEdit_Name = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_Name.setFont(font)
        self.lineEdit_Name.setObjectName("lineEdit_Name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Name)
        self.lineEdit_Password = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_Password.setFont(font)
        self.lineEdit_Password.setObjectName("lineEdit_Password")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Password)
        self.push_AceptAuthoriz = QtWidgets.QPushButton(self.centralwidget)
        self.push_AceptAuthoriz.setGeometry(QtCore.QRect(10, 190, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.push_AceptAuthoriz.setFont(font)
        self.push_AceptAuthoriz.setObjectName("push_AceptAuthoriz")
        self.push_GoBack = QtWidgets.QPushButton(self.centralwidget)
        self.push_GoBack.setGeometry(QtCore.QRect(260, 190, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.push_GoBack.setFont(font)
        self.push_GoBack.setObjectName("push_GoBack")
        AuthorizationWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(AuthorizationWindow)
        QtCore.QMetaObject.connectSlotsByName(AuthorizationWindow)

    def retranslateUi(self, AuthorizationWindow):
        _translate = QtCore.QCoreApplication.translate
        AuthorizationWindow.setWindowTitle(_translate("AuthorizationWindow", "Авторизация"))
        self.label_Authorization.setText(_translate("AuthorizationWindow", "Авторизация"))
        self.label_Name.setText(_translate("AuthorizationWindow", "Имя"))
        self.label_Password.setText(_translate("AuthorizationWindow", "Пароль"))
        self.push_AceptAuthoriz.setText(_translate("AuthorizationWindow", "Войти!!!"))
        self.push_GoBack.setText(_translate("AuthorizationWindow", "Отмена((("))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AuthorizationWindow = QtWidgets.QMainWindow()
    ui = Ui_AuthorizationWindow()
    ui.setupUi(AuthorizationWindow)
    AuthorizationWindow.show()
    sys.exit(app.exec_())
