# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\from_designer\CreateCharacter_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateCharacterWidget(object):
    def setupUi(self, CreateCharacterWidget):
        CreateCharacterWidget.setObjectName("CreateCharacterWidget")
        CreateCharacterWidget.resize(400, 250)
        CreateCharacterWidget.setMinimumSize(QtCore.QSize(400, 250))
        CreateCharacterWidget.setMaximumSize(QtCore.QSize(400, 250))
        self.push_CreateCharacter = QtWidgets.QPushButton(CreateCharacterWidget)
        self.push_CreateCharacter.setGeometry(QtCore.QRect(10, 200, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(18)
        self.push_CreateCharacter.setFont(font)
        self.push_CreateCharacter.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0.0340909, stop:0 rgba(61, 61, 61, 255), stop:1 rgba(124, 124, 124, 255));\n"
"color: rgb(255, 253, 189)")
        self.push_CreateCharacter.setObjectName("push_CreateCharacter")
        self.push_GoBack = QtWidgets.QPushButton(CreateCharacterWidget)
        self.push_GoBack.setGeometry(QtCore.QRect(240, 200, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(18)
        self.push_GoBack.setFont(font)
        self.push_GoBack.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0.0340909, stop:0 rgba(61, 61, 61, 255), stop:1 rgba(124, 124, 124, 255));\n"
"color: rgb(255, 253, 189)")
        self.push_GoBack.setObjectName("push_GoBack")
        self.title = QtWidgets.QLabel(CreateCharacterWidget)
        self.title.setGeometry(QtCore.QRect(110, 10, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(22)
        self.title.setFont(font)
        self.title.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"")
        self.title.setObjectName("title")
        self.img_title = QtWidgets.QLabel(CreateCharacterWidget)
        self.img_title.setGeometry(QtCore.QRect(70, 10, 251, 41))
        self.img_title.setStyleSheet("")
        self.img_title.setText("")
        self.img_title.setPixmap(QtGui.QPixmap(":/pins1/pergament2.png"))
        self.img_title.setScaledContents(True)
        self.img_title.setObjectName("img_title")
        self.img_background = QtWidgets.QLabel(CreateCharacterWidget)
        self.img_background.setGeometry(QtCore.QRect(0, 0, 400, 250))
        self.img_background.setStyleSheet("background-image: url(:/newPrefix/Desktop/Прочее/Vorota.png);")
        self.img_background.setText("")
        self.img_background.setPixmap(QtGui.QPixmap(":/pins1/heroes.jpg"))
        self.img_background.setScaledContents(True)
        self.img_background.setObjectName("img_background")
        self.formLayoutWidget = QtWidgets.QWidget(CreateCharacterWidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(50, 70, 301, 121))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.Name = QtWidgets.QLabel(self.formLayoutWidget)
        self.Name.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(18)
        self.Name.setFont(font)
        self.Name.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0.0340909, stop:0 rgba(61, 61, 61, 255), stop:1 rgba(124, 124, 124, 255));\n"
"color: rgb(255, 253, 189)")
        self.Name.setObjectName("Name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Name)
        self.LineEdit_Name = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.LineEdit_Name.setFont(font)
        self.LineEdit_Name.setObjectName("LineEdit_Name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LineEdit_Name)
        self.Race = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(18)
        self.Race.setFont(font)
        self.Race.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0.0340909, stop:0 rgba(61, 61, 61, 255), stop:1 rgba(124, 124, 124, 255));\n"
"color: rgb(255, 253, 189)")
        self.Race.setObjectName("Race")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Race)
        self.LineEdit_Race = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.LineEdit_Race.setFont(font)
        self.LineEdit_Race.setObjectName("LineEdit_Race")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LineEdit_Race)
        self.Spec = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.Spec.setFont(font)
        self.Spec.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0.0340909, stop:0 rgba(61, 61, 61, 255), stop:1 rgba(124, 124, 124, 255));\n"
"color: rgb(255, 253, 189)")
        self.Spec.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Spec.setObjectName("Spec")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Spec)
        self.LineEdit_Spec = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.LineEdit_Spec.setFont(font)
        self.LineEdit_Spec.setObjectName("LineEdit_Spec")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.LineEdit_Spec)
        self.img_background.raise_()
        self.img_title.raise_()
        self.push_CreateCharacter.raise_()
        self.push_GoBack.raise_()
        self.title.raise_()
        self.formLayoutWidget.raise_()

        self.retranslateUi(CreateCharacterWidget)
        QtCore.QMetaObject.connectSlotsByName(CreateCharacterWidget)

    def retranslateUi(self, CreateCharacterWidget):
        _translate = QtCore.QCoreApplication.translate
        CreateCharacterWidget.setWindowTitle(_translate("CreateCharacterWidget", "Создание героя"))
        self.push_CreateCharacter.setText(_translate("CreateCharacterWidget", "Создать героя"))
        self.push_GoBack.setText(_translate("CreateCharacterWidget", "Отмена"))
        self.title.setText(_translate("CreateCharacterWidget", "Создание Героя"))
        self.Name.setText(_translate("CreateCharacterWidget", " Имя "))
        self.Race.setText(_translate("CreateCharacterWidget", " Раса "))
        self.Spec.setText(_translate("CreateCharacterWidget", "Класс"))
import images.resource1_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CreateCharacterWidget = QtWidgets.QWidget()
    ui = Ui_CreateCharacterWidget()
    ui.setupUi(CreateCharacterWidget)
    CreateCharacterWidget.show()
    sys.exit(app.exec_())
