# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\from_designer\CreateRace_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateRaceWidget(object):
    def setupUi(self, CreateRaceWidget):
        CreateRaceWidget.setObjectName("CreateRaceWidget")
        CreateRaceWidget.resize(400, 250)
        CreateRaceWidget.setMinimumSize(QtCore.QSize(400, 250))
        CreateRaceWidget.setMaximumSize(QtCore.QSize(400, 250))
        self.push_AceptCreate = QtWidgets.QPushButton(CreateRaceWidget)
        self.push_AceptCreate.setGeometry(QtCore.QRect(10, 200, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(18)
        self.push_AceptCreate.setFont(font)
        self.push_AceptCreate.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0.0340909, stop:0 rgba(61, 61, 61, 255), stop:1 rgba(124, 124, 124, 255));\n"
"color: rgb(255, 253, 189)")
        self.push_AceptCreate.setObjectName("push_AceptCreate")
        self.push_GoBack = QtWidgets.QPushButton(CreateRaceWidget)
        self.push_GoBack.setGeometry(QtCore.QRect(240, 200, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(18)
        self.push_GoBack.setFont(font)
        self.push_GoBack.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0.0340909, stop:0 rgba(61, 61, 61, 255), stop:1 rgba(124, 124, 124, 255));\n"
"color: rgb(255, 253, 189)")
        self.push_GoBack.setObjectName("push_GoBack")
        self.formLayoutWidget = QtWidgets.QWidget(CreateRaceWidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(50, 100, 291, 41))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_Name = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(18)
        self.label_Name.setFont(font)
        self.label_Name.setStyleSheet("background-color: rgb(61, 61, 61);\n"
"color: rgb(255, 253, 189)")
        self.label_Name.setObjectName("label_Name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_Name)
        self.lineEdit_Name = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lineEdit_Name.setFont(font)
        self.lineEdit_Name.setObjectName("lineEdit_Name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Name)
        self.label_Race = QtWidgets.QLabel(CreateRaceWidget)
        self.label_Race.setGeometry(QtCore.QRect(120, 10, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(22)
        self.label_Race.setFont(font)
        self.label_Race.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"")
        self.label_Race.setObjectName("label_Race")
        self.img_underRace = QtWidgets.QLabel(CreateRaceWidget)
        self.img_underRace.setGeometry(QtCore.QRect(80, 10, 241, 41))
        self.img_underRace.setStyleSheet("background-image: url(:/newPrefix/Downloads/kisspng-paper-scroll-parchment-clip-art-landscape-apge-with-pen-5b0bcdc6e5bf67.4688394015275002309411.png);")
        self.img_underRace.setText("")
        self.img_underRace.setPixmap(QtGui.QPixmap(":/pins1/pergament2.png"))
        self.img_underRace.setScaledContents(True)
        self.img_underRace.setObjectName("img_underRace")
        self.img_background = QtWidgets.QLabel(CreateRaceWidget)
        self.img_background.setGeometry(QtCore.QRect(0, 0, 400, 250))
        self.img_background.setMinimumSize(QtCore.QSize(400, 250))
        self.img_background.setMaximumSize(QtCore.QSize(400, 250))
        self.img_background.setStyleSheet("background-image: url(:/newPrefix/Desktop/Прочее/Lab.png);")
        self.img_background.setText("")
        self.img_background.setPixmap(QtGui.QPixmap(":/pins1/heroes.jpg"))
        self.img_background.setScaledContents(True)
        self.img_background.setObjectName("img_background")
        self.img_background.raise_()
        self.img_underRace.raise_()
        self.push_AceptCreate.raise_()
        self.push_GoBack.raise_()
        self.formLayoutWidget.raise_()
        self.label_Race.raise_()

        self.retranslateUi(CreateRaceWidget)
        QtCore.QMetaObject.connectSlotsByName(CreateRaceWidget)

    def retranslateUi(self, CreateRaceWidget):
        _translate = QtCore.QCoreApplication.translate
        CreateRaceWidget.setWindowTitle(_translate("CreateRaceWidget", "Создание расы"))
        self.push_AceptCreate.setText(_translate("CreateRaceWidget", "Создать"))
        self.push_GoBack.setText(_translate("CreateRaceWidget", "Отмена"))
        self.label_Name.setText(_translate("CreateRaceWidget", "Название"))
        self.label_Race.setText(_translate("CreateRaceWidget", "Создание расы"))
import images.resource1_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CreateRaceWidget = QtWidgets.QWidget()
    ui = Ui_CreateRaceWidget()
    ui.setupUi(CreateRaceWidget)
    CreateRaceWidget.show()
    sys.exit(app.exec_())
