# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ClassMake_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ClassMake(object):
    def setupUi(self, ClassMake):
        ClassMake.setObjectName("ClassMake")
        ClassMake.resize(400, 250)
        ClassMake.setMinimumSize(QtCore.QSize(400, 250))
        ClassMake.setMaximumSize(QtCore.QSize(400, 250))
        self.push_AceptAuthoriz = QtWidgets.QPushButton(ClassMake)
        self.push_AceptAuthoriz.setGeometry(QtCore.QRect(10, 200, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(18)
        self.push_AceptAuthoriz.setFont(font)
        self.push_AceptAuthoriz.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0.0340909, stop:0 rgba(61, 61, 61, 255), stop:1 rgba(124, 124, 124, 255));\n"
"color: rgb(255, 253, 189)")
        self.push_AceptAuthoriz.setObjectName("push_AceptAuthoriz")
        self.push_GoBack = QtWidgets.QPushButton(ClassMake)
        self.push_GoBack.setGeometry(QtCore.QRect(240, 200, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(16)
        self.push_GoBack.setFont(font)
        self.push_GoBack.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0.0340909, stop:0 rgba(61, 61, 61, 255), stop:1 rgba(124, 124, 124, 255));\n"
"color: rgb(255, 253, 189)")
        self.push_GoBack.setObjectName("push_GoBack")
        self.formLayoutWidget = QtWidgets.QWidget(ClassMake)
        self.formLayoutWidget.setGeometry(QtCore.QRect(50, 90, 291, 41))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_Name = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        self.label_Name.setFont(font)
        self.label_Name.setStyleSheet("background-color: rgb(61, 61, 61);\n"
"color: rgb(255, 253, 189)")
        self.label_Name.setObjectName("label_Name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_Name)
        self.lineEdit_Name = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_Name.setFont(font)
        self.lineEdit_Name.setObjectName("lineEdit_Name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Name)
        self.label_Authorization = QtWidgets.QLabel(ClassMake)
        self.label_Authorization.setGeometry(QtCore.QRect(110, 10, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(22)
        self.label_Authorization.setFont(font)
        self.label_Authorization.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"")
        self.label_Authorization.setObjectName("label_Authorization")
        self.img_underAuthoriz = QtWidgets.QLabel(ClassMake)
        self.img_underAuthoriz.setGeometry(QtCore.QRect(60, 10, 281, 41))
        self.img_underAuthoriz.setStyleSheet("background-image: url(:/newPrefix/Downloads/kisspng-paper-scroll-parchment-clip-art-landscape-apge-with-pen-5b0bcdc6e5bf67.4688394015275002309411.png);")
        self.img_underAuthoriz.setText("")
        self.img_underAuthoriz.setPixmap(QtGui.QPixmap(":/newPrefix/Downloads/kisspng-paper-scroll-parchment-clip-art-landscape-apge-with-pen-5b0bcdc6e5bf67.4688394015275002309411.png"))
        self.img_underAuthoriz.setScaledContents(True)
        self.img_underAuthoriz.setObjectName("img_underAuthoriz")
        self.img_background = QtWidgets.QLabel(ClassMake)
        self.img_background.setGeometry(QtCore.QRect(0, 0, 400, 250))
        self.img_background.setMinimumSize(QtCore.QSize(400, 250))
        self.img_background.setMaximumSize(QtCore.QSize(400, 250))
        self.img_background.setStyleSheet("background-image: url(:/newPrefix/Desktop/Прочее/ca2c1866ea4cc5d07e622ab207ddc622.jpg);")
        self.img_background.setText("")
        self.img_background.setPixmap(QtGui.QPixmap(":/newPrefix/Desktop/Прочее/ca2c1866ea4cc5d07e622ab207ddc622.jpg"))
        self.img_background.setScaledContents(True)
        self.img_background.setObjectName("img_background")
        self.img_background.raise_()
        self.img_underAuthoriz.raise_()
        self.push_AceptAuthoriz.raise_()
        self.push_GoBack.raise_()
        self.formLayoutWidget.raise_()
        self.label_Authorization.raise_()

        self.retranslateUi(ClassMake)
        QtCore.QMetaObject.connectSlotsByName(ClassMake)

    def retranslateUi(self, ClassMake):
        _translate = QtCore.QCoreApplication.translate
        ClassMake.setWindowTitle(_translate("ClassMake", "Создание_класса"))
        self.push_AceptAuthoriz.setText(_translate("ClassMake", "Создать профессию!"))
        self.push_GoBack.setText(_translate("ClassMake", "Я передумал..."))
        self.label_Name.setText(_translate("ClassMake", "Название"))
        self.label_Authorization.setText(_translate("ClassMake", "Создание класса"))
import test_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ClassMake = QtWidgets.QWidget()
    ui = Ui_ClassMake()
    ui.setupUi(ClassMake)
    ClassMake.show()
    sys.exit(app.exec_())
