# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\from_designer\ChangeCharacter_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChangeCharacterWidget(object):
    def setupUi(self, ChangeCharacterWidget):
        ChangeCharacterWidget.setObjectName("ChangeCharacterWidget")
        ChangeCharacterWidget.resize(400, 250)
        ChangeCharacterWidget.setMinimumSize(QtCore.QSize(400, 250))
        ChangeCharacterWidget.setMaximumSize(QtCore.QSize(400, 250))
        self.push_GoBack = QtWidgets.QPushButton(ChangeCharacterWidget)
        self.push_GoBack.setGeometry(QtCore.QRect(240, 200, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(18)
        font.setItalic(False)
        self.push_GoBack.setFont(font)
        self.push_GoBack.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0.0340909, stop:0 rgba(61, 61, 61, 255), stop:1 rgba(124, 124, 124, 255));\n"
"color: rgb(255, 253, 189)")
        self.push_GoBack.setObjectName("push_GoBack")
        self.title = QtWidgets.QLabel(ChangeCharacterWidget)
        self.title.setGeometry(QtCore.QRect(90, 10, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(22)
        self.title.setFont(font)
        self.title.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"")
        self.title.setObjectName("title")
        self.img_title = QtWidgets.QLabel(ChangeCharacterWidget)
        self.img_title.setGeometry(QtCore.QRect(40, 10, 321, 41))
        self.img_title.setStyleSheet("")
        self.img_title.setText("")
        self.img_title.setPixmap(QtGui.QPixmap(":/pins1/pergament2.png"))
        self.img_title.setScaledContents(True)
        self.img_title.setObjectName("img_title")
        self.img_background = QtWidgets.QLabel(ChangeCharacterWidget)
        self.img_background.setGeometry(QtCore.QRect(0, 0, 400, 250))
        self.img_background.setStyleSheet("background-image: url(:/newPrefix/Desktop/Прочее/Vorota.png);")
        self.img_background.setText("")
        self.img_background.setPixmap(QtGui.QPixmap(":/pins1/heroes.jpg"))
        self.img_background.setScaledContents(True)
        self.img_background.setObjectName("img_background")
        self.formLayoutWidget_2 = QtWidgets.QWidget(ChangeCharacterWidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(20, 90, 361, 81))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.push_levelUp = QtWidgets.QPushButton(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(16)
        self.push_levelUp.setFont(font)
        self.push_levelUp.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0.0340909, stop:0 rgba(61, 61, 61, 255), stop:1 rgba(124, 124, 124, 255));\n"
"color: rgb(255, 253, 189)")
        self.push_levelUp.setObjectName("push_levelUp")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.push_levelUp)
        self.label_level = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(18)
        self.label_level.setFont(font)
        self.label_level.setStyleSheet("background-color: rgb(244, 244, 244);")
        self.label_level.setText("")
        self.label_level.setObjectName("label_level")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_level)
        self.push_changeGuild = QtWidgets.QPushButton(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(16)
        self.push_changeGuild.setFont(font)
        self.push_changeGuild.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0.0340909, stop:0 rgba(61, 61, 61, 255), stop:1 rgba(124, 124, 124, 255));\n"
"color: rgb(255, 253, 189)")
        self.push_changeGuild.setObjectName("push_changeGuild")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.push_changeGuild)
        self.comboBox = QtWidgets.QComboBox(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(18)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.push_delete = QtWidgets.QPushButton(ChangeCharacterWidget)
        self.push_delete.setGeometry(QtCore.QRect(20, 202, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(18)
        self.push_delete.setFont(font)
        self.push_delete.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0.0340909, stop:0 rgba(61, 61, 61, 255), stop:1 rgba(124, 124, 124, 255));\n"
"color: rgb(255, 253, 189)")
        self.push_delete.setObjectName("push_delete")
        self.img_background.raise_()
        self.img_title.raise_()
        self.push_GoBack.raise_()
        self.title.raise_()
        self.formLayoutWidget_2.raise_()
        self.push_delete.raise_()

        self.retranslateUi(ChangeCharacterWidget)
        QtCore.QMetaObject.connectSlotsByName(ChangeCharacterWidget)

    def retranslateUi(self, ChangeCharacterWidget):
        _translate = QtCore.QCoreApplication.translate
        ChangeCharacterWidget.setWindowTitle(_translate("ChangeCharacterWidget", "Изменение персонажа"))
        self.push_GoBack.setText(_translate("ChangeCharacterWidget", "Назад"))
        self.title.setText(_translate("ChangeCharacterWidget", "Измение персонажа"))
        self.push_levelUp.setText(_translate("ChangeCharacterWidget", "Повысить уровень"))
        self.push_changeGuild.setText(_translate("ChangeCharacterWidget", "Сменить гильдию "))
        self.push_delete.setText(_translate("ChangeCharacterWidget", "Удалить"))
import images.resource1_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ChangeCharacterWidget = QtWidgets.QWidget()
    ui = Ui_ChangeCharacterWidget()
    ui.setupUi(ChangeCharacterWidget)
    ChangeCharacterWidget.show()
    sys.exit(app.exec_())
