# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\from_designer\Entrance_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EntranceWindow(object):
    def setupUi(self, EntranceWindow):
        EntranceWindow.setObjectName("EntranceWindow")
        EntranceWindow.resize(700, 500)
        EntranceWindow.setMinimumSize(QtCore.QSize(700, 500))
        EntranceWindow.setMaximumSize(QtCore.QSize(700, 500))
        self.centralwidget = QtWidgets.QWidget(EntranceWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LogIn = QtWidgets.QPushButton(self.centralwidget)
        self.LogIn.setGeometry(QtCore.QRect(230, 180, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(24)
        self.LogIn.setFont(font)
        self.LogIn.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0.0340909, stop:0 rgba(61, 61, 61, 255), stop:1 rgba(124, 124, 124, 255));\n"
"color: rgb(255, 253, 189)")
        self.LogIn.setObjectName("LogIn")
        self.Exit = QtWidgets.QPushButton(self.centralwidget)
        self.Exit.setGeometry(QtCore.QRect(230, 360, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(19)
        self.Exit.setFont(font)
        self.Exit.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0.0340909, stop:0 rgba(61, 61, 61, 255), stop:1 rgba(124, 124, 124, 255));\n"
"color: rgb(255, 253, 189)")
        self.Exit.setObjectName("Exit")
        self.SignUp = QtWidgets.QPushButton(self.centralwidget)
        self.SignUp.setGeometry(QtCore.QRect(230, 270, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(24)
        self.SignUp.setFont(font)
        self.SignUp.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0.0340909, stop:0 rgba(61, 61, 61, 255), stop:1 rgba(124, 124, 124, 255));\n"
"color: rgb(255, 253, 189)")
        self.SignUp.setObjectName("SignUp")
        self.backImage = QtWidgets.QLabel(self.centralwidget)
        self.backImage.setGeometry(QtCore.QRect(0, 0, 701, 501))
        self.backImage.setStyleSheet("image: url(:/pins1/zastavochka1.png);")
        self.backImage.setText("")
        self.backImage.setPixmap(QtGui.QPixmap(":/pins1/zastavochka1.png"))
        self.backImage.setScaledContents(True)
        self.backImage.setObjectName("backImage")
        self.backImage.raise_()
        self.LogIn.raise_()
        self.Exit.raise_()
        self.SignUp.raise_()
        EntranceWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(EntranceWindow)
        QtCore.QMetaObject.connectSlotsByName(EntranceWindow)

    def retranslateUi(self, EntranceWindow):
        _translate = QtCore.QCoreApplication.translate
        EntranceWindow.setWindowTitle(_translate("EntranceWindow", "Вход"))
        self.LogIn.setText(_translate("EntranceWindow", "Войти"))
        self.Exit.setText(_translate("EntranceWindow", "Выйти из приложения"))
        self.SignUp.setText(_translate("EntranceWindow", "Регистрация"))
import images.resource1_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EntranceWindow = QtWidgets.QMainWindow()
    ui = Ui_EntranceWindow()
    ui.setupUi(EntranceWindow)
    EntranceWindow.show()
    sys.exit(app.exec_())
