# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\from_designer\Guilds_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GuildsWindow(object):
    def setupUi(self, GuildsWindow):
        GuildsWindow.setObjectName("GuildsWindow")
        GuildsWindow.resize(700, 500)
        GuildsWindow.setMinimumSize(QtCore.QSize(700, 500))
        GuildsWindow.setMaximumSize(QtCore.QSize(700, 500))
        self.centralwidget = QtWidgets.QWidget(GuildsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.push_createGuild = QtWidgets.QPushButton(self.centralwidget)
        self.push_createGuild.setGeometry(QtCore.QRect(30, 440, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(18)
        self.push_createGuild.setFont(font)
        self.push_createGuild.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0.0340909, stop:0 rgba(61, 61, 61, 255), stop:1 rgba(124, 124, 124, 255));\n"
"color: rgb(255, 253, 189)")
        self.push_createGuild.setObjectName("push_createGuild")
        self.Title = QtWidgets.QLabel(self.centralwidget)
        self.Title.setGeometry(QtCore.QRect(250, 10, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(32)
        self.Title.setFont(font)
        self.Title.setStyleSheet("")
        self.Title.setObjectName("Title")
        self.push_goBack = QtWidgets.QPushButton(self.centralwidget)
        self.push_goBack.setGeometry(QtCore.QRect(500, 440, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(18)
        self.push_goBack.setFont(font)
        self.push_goBack.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0.0340909, stop:0 rgba(61, 61, 61, 255), stop:1 rgba(124, 124, 124, 255));\n"
"color: rgb(255, 253, 189)")
        self.push_goBack.setObjectName("push_goBack")
        self.tableWidget_Guilds = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_Guilds.setEnabled(True)
        self.tableWidget_Guilds.setGeometry(QtCore.QRect(20, 60, 661, 371))
        self.tableWidget_Guilds.setStyleSheet("border-image: url(:/pins1/pergament4.jpg);")
        self.tableWidget_Guilds.setAutoScroll(True)
        self.tableWidget_Guilds.setObjectName("tableWidget_Guilds")
        self.tableWidget_Guilds.setColumnCount(3)
        self.tableWidget_Guilds.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Guilds.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Guilds.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Guilds.setHorizontalHeaderItem(2, item)
        self.img_background = QtWidgets.QLabel(self.centralwidget)
        self.img_background.setGeometry(QtCore.QRect(0, 0, 700, 500))
        self.img_background.setMinimumSize(QtCore.QSize(700, 500))
        self.img_background.setMaximumSize(QtCore.QSize(700, 500))
        self.img_background.setStyleSheet("")
        self.img_background.setText("")
        self.img_background.setPixmap(QtGui.QPixmap(":/pins1/guilds.jpg"))
        self.img_background.setScaledContents(True)
        self.img_background.setObjectName("img_background")
        self.img_underGuilds = QtWidgets.QLabel(self.centralwidget)
        self.img_underGuilds.setGeometry(QtCore.QRect(220, 10, 201, 41))
        self.img_underGuilds.setText("")
        self.img_underGuilds.setPixmap(QtGui.QPixmap(":/pins1/pergament2.png"))
        self.img_underGuilds.setScaledContents(True)
        self.img_underGuilds.setObjectName("img_underGuilds")
        self.img_background.raise_()
        self.img_underGuilds.raise_()
        self.push_createGuild.raise_()
        self.Title.raise_()
        self.push_goBack.raise_()
        self.tableWidget_Guilds.raise_()
        GuildsWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(GuildsWindow)
        QtCore.QMetaObject.connectSlotsByName(GuildsWindow)

    def retranslateUi(self, GuildsWindow):
        _translate = QtCore.QCoreApplication.translate
        GuildsWindow.setWindowTitle(_translate("GuildsWindow", "Гильдии"))
        self.push_createGuild.setText(_translate("GuildsWindow", "Создать гильдию"))
        self.Title.setText(_translate("GuildsWindow", "Гильдии"))
        self.push_goBack.setText(_translate("GuildsWindow", "Назад"))
        item = self.tableWidget_Guilds.horizontalHeaderItem(0)
        item.setText(_translate("GuildsWindow", "id"))
        item = self.tableWidget_Guilds.horizontalHeaderItem(1)
        item.setText(_translate("GuildsWindow", "Название"))
        item = self.tableWidget_Guilds.horizontalHeaderItem(2)
        item.setText(_translate("GuildsWindow", "Число участников"))
import images.resource1_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GuildsWindow = QtWidgets.QMainWindow()
    ui = Ui_GuildsWindow()
    ui.setupUi(GuildsWindow)
    GuildsWindow.show()
    sys.exit(app.exec_())
