
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegistrationWindow(object):
    def setupUi(self, RegistrationWindow):
        RegistrationWindow.setObjectName("RegistrationWindow")
        RegistrationWindow.resize(400, 250)
        self.centralwidget = QtWidgets.QWidget(RegistrationWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_Registration = QtWidgets.QLabel(self.centralwidget)
        self.label_Registration.setGeometry(QtCore.QRect(20, 30, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_Registration.setFont(font)
        self.label_Registration.setObjectName("label_Registration")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(50, 90, 291, 71))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_Name = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_Name.setFont(font)
        self.label_Name.setObjectName("label_Name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_Name)
        self.label_Password = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_Password.setFont(font)
        self.label_Password.setObjectName("label_Password")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_Password)
        self.lineEdit_Name = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_Name.setFont(font)
        self.lineEdit_Name.setObjectName("lineEdit_Name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Name)
        self.lineEdit_Password = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_Password.setFont(font)
        self.lineEdit_Password.setObjectName("lineEdit_Password")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Password)
        self.push_AceptRegist = QtWidgets.QPushButton(self.centralwidget)
        self.push_AceptRegist.setGeometry(QtCore.QRect(10, 190, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.push_AceptRegist.setFont(font)
        self.push_AceptRegist.setObjectName("push_AceptRegist")
        self.push_GoBack = QtWidgets.QPushButton(self.centralwidget)
        self.push_GoBack.setGeometry(QtCore.QRect(260, 190, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.push_GoBack.setFont(font)
        self.push_GoBack.setObjectName("push_GoBack")
        RegistrationWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(RegistrationWindow)
        QtCore.QMetaObject.connectSlotsByName(RegistrationWindow)

    def retranslateUi(self, RegistrationWindow):
        _translate = QtCore.QCoreApplication.translate
        RegistrationWindow.setWindowTitle(_translate("RegistrationWindow", "Регистрация"))
        self.label_Registration.setText(_translate("RegistrationWindow", "Регистрация"))
        self.label_Name.setText(_translate("RegistrationWindow", "Имя"))
        self.label_Password.setText(_translate("RegistrationWindow", "Пароль"))
        self.push_AceptRegist.setText(_translate("RegistrationWindow", "Зарегестрироваться!!!"))
        self.push_GoBack.setText(_translate("RegistrationWindow", "Отмена((("))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RegistrationWindow = QtWidgets.QMainWindow()
    ui = Ui_RegistrationWindow()
    ui.setupUi(RegistrationWindow)
    RegistrationWindow.show()
    sys.exit(app.exec_())
