
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RacesSpecsWindow(object):
    def setupUi(self, RacesSpecsWindow):
        RacesSpecsWindow.setObjectName("RacesSpecsWindow")
        RacesSpecsWindow.resize(700, 500)
        self.centralwidget = QtWidgets.QWidget(RacesSpecsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Title = QtWidgets.QLabel(self.centralwidget)
        self.Title.setGeometry(QtCore.QRect(30, 10, 631, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.Title.setFont(font)
        self.Title.setObjectName("Title")
        self.tableWidget_Races = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_Races.setGeometry(QtCore.QRect(20, 110, 181, 271))
        self.tableWidget_Races.setObjectName("tableWidget_Races")
        self.tableWidget_Races.setColumnCount(2)
        self.tableWidget_Races.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Races.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Races.setHorizontalHeaderItem(1, item)
        self.label_Races = QtWidgets.QLabel(self.centralwidget)
        self.label_Races.setGeometry(QtCore.QRect(20, 80, 161, 31))
        self.label_Races.setObjectName("label_Races")
        self.label_RacesSpecs = QtWidgets.QLabel(self.centralwidget)
        self.label_RacesSpecs.setGeometry(QtCore.QRect(430, 80, 161, 31))
        self.label_RacesSpecs.setObjectName("label_RacesSpecs")
        self.tableWidget_Specs = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_Specs.setGeometry(QtCore.QRect(210, 110, 181, 271))
        self.tableWidget_Specs.setObjectName("tableWidget_Specs")
        self.tableWidget_Specs.setColumnCount(2)
        self.tableWidget_Specs.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Specs.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Specs.setHorizontalHeaderItem(1, item)
        self.push_addRace = QtWidgets.QPushButton(self.centralwidget)
        self.push_addRace.setGeometry(QtCore.QRect(50, 390, 121, 41))
        self.push_addRace.setObjectName("push_addRace")
        self.label_Specs = QtWidgets.QLabel(self.centralwidget)
        self.label_Specs.setGeometry(QtCore.QRect(210, 80, 161, 31))
        self.label_Specs.setObjectName("label_Specs")
        self.tableWidget_RacesSpecs = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_RacesSpecs.setGeometry(QtCore.QRect(430, 110, 221, 271))
        self.tableWidget_RacesSpecs.setObjectName("tableWidget_RacesSpecs")
        self.tableWidget_RacesSpecs.setColumnCount(2)
        self.tableWidget_RacesSpecs.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_RacesSpecs.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_RacesSpecs.setHorizontalHeaderItem(1, item)
        self.push_addSpec = QtWidgets.QPushButton(self.centralwidget)
        self.push_addSpec.setGeometry(QtCore.QRect(240, 390, 121, 41))
        self.push_addSpec.setObjectName("push_addSpec")
        self.push_goBack = QtWidgets.QPushButton(self.centralwidget)
        self.push_goBack.setGeometry(QtCore.QRect(500, 440, 171, 41))
        self.push_goBack.setObjectName("push_goBack")
        self.push_addRaceSpec = QtWidgets.QPushButton(self.centralwidget)
        self.push_addRaceSpec.setGeometry(QtCore.QRect(480, 390, 121, 41))
        self.push_addRaceSpec.setObjectName("push_addRaceSpec")
        RacesSpecsWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(RacesSpecsWindow)
        QtCore.QMetaObject.connectSlotsByName(RacesSpecsWindow)

    def retranslateUi(self, RacesSpecsWindow):
        _translate = QtCore.QCoreApplication.translate
        RacesSpecsWindow.setWindowTitle(_translate("RacesSpecsWindow", "Расы и классы"))
        self.Title.setText(_translate("RacesSpecsWindow", "Расы и классы"))
        item = self.tableWidget_Races.horizontalHeaderItem(0)
        item.setText(_translate("RacesSpecsWindow", "id"))
        item = self.tableWidget_Races.horizontalHeaderItem(1)
        item.setText(_translate("RacesSpecsWindow", "Раса"))
        self.label_Races.setText(_translate("RacesSpecsWindow", "Расы"))
        self.label_RacesSpecs.setText(_translate("RacesSpecsWindow", "Расы и классы"))
        item = self.tableWidget_Specs.horizontalHeaderItem(0)
        item.setText(_translate("RacesSpecsWindow", "id"))
        item = self.tableWidget_Specs.horizontalHeaderItem(1)
        item.setText(_translate("RacesSpecsWindow", "Класс"))
        self.push_addRace.setText(_translate("RacesSpecsWindow", "Добавить"))
        self.label_Specs.setText(_translate("RacesSpecsWindow", "Классы"))
        item = self.tableWidget_RacesSpecs.horizontalHeaderItem(0)
        item.setText(_translate("RacesSpecsWindow", "Расы"))
        item = self.tableWidget_RacesSpecs.horizontalHeaderItem(1)
        item.setText(_translate("RacesSpecsWindow", "Классы"))
        self.push_addSpec.setText(_translate("RacesSpecsWindow", "Добавить"))
        self.push_goBack.setText(_translate("RacesSpecsWindow", "Назад"))
        self.push_addRaceSpec.setText(_translate("RacesSpecsWindow", "Добавить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RacesSpecsWindow = QtWidgets.QMainWindow()
    ui = Ui_RacesSpecsWindow()
    ui.setupUi(RacesSpecsWindow)
    RacesSpecsWindow.show()
    sys.exit(app.exec_())
