# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\from_designer\Registration_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegistrationWidget(object):
    def setupUi(self, RegistrationWidget):
        RegistrationWidget.setObjectName("RegistrationWidget")
        RegistrationWidget.resize(400, 250)
        RegistrationWidget.setMinimumSize(QtCore.QSize(400, 250))
        RegistrationWidget.setMaximumSize(QtCore.QSize(400, 250))
        self.img_background = QtWidgets.QLabel(RegistrationWidget)
        self.img_background.setGeometry(QtCore.QRect(0, 0, 400, 250))
        self.img_background.setStyleSheet("background-image: url(:/newPrefix/Desktop/Прочее/Vorota.png);")
        self.img_background.setText("")
        self.img_background.setPixmap(QtGui.QPixmap(":/pins1/VOROTA1.jpg"))
        self.img_background.setScaledContents(True)
        self.img_background.setObjectName("img_background")
        self.formLayoutWidget = QtWidgets.QWidget(RegistrationWidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(50, 90, 291, 78))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_Name = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(18)
        self.label_Name.setFont(font)
        self.label_Name.setStyleSheet("background-color: rgb(61, 61, 61);\n"
"color: rgb(255, 253, 189)")
        self.label_Name.setObjectName("label_Name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_Name)
        self.label_Password = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(18)
        self.label_Password.setFont(font)
        self.label_Password.setStyleSheet("background-color: rgb(61, 61, 61);\n"
"color: rgb(255, 253, 189)\n"
"")
        self.label_Password.setObjectName("label_Password")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_Password)
        self.lineEdit_Name = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(18)
        self.lineEdit_Name.setFont(font)
        self.lineEdit_Name.setObjectName("lineEdit_Name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Name)
        self.lineEdit_Password = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(18)
        self.lineEdit_Password.setFont(font)
        self.lineEdit_Password.setObjectName("lineEdit_Password")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Password)
        self.push_GoBack = QtWidgets.QPushButton(RegistrationWidget)
        self.push_GoBack.setGeometry(QtCore.QRect(240, 200, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(18)
        self.push_GoBack.setFont(font)
        self.push_GoBack.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0.0340909, stop:0 rgba(61, 61, 61, 255), stop:1 rgba(124, 124, 124, 255));\n"
"color: rgb(255, 253, 189)")
        self.push_GoBack.setObjectName("push_GoBack")
        self.label_Registration = QtWidgets.QLabel(RegistrationWidget)
        self.label_Registration.setGeometry(QtCore.QRect(120, 10, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(22)
        self.label_Registration.setFont(font)
        self.label_Registration.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"")
        self.label_Registration.setObjectName("label_Registration")
        self.push_AceptRegist = QtWidgets.QPushButton(RegistrationWidget)
        self.push_AceptRegist.setGeometry(QtCore.QRect(10, 200, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(18)
        self.push_AceptRegist.setFont(font)
        self.push_AceptRegist.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0.0340909, stop:0 rgba(61, 61, 61, 255), stop:1 rgba(124, 124, 124, 255));\n"
"color: rgb(255, 253, 189)")
        self.push_AceptRegist.setObjectName("push_AceptRegist")
        self.img_underRegist = QtWidgets.QLabel(RegistrationWidget)
        self.img_underRegist.setGeometry(QtCore.QRect(90, 10, 211, 41))
        self.img_underRegist.setStyleSheet("background-image: url(:/newPrefix/Downloads/kisspng-paper-scroll-parchment-clip-art-landscape-apge-with-pen-5b0bcdc6e5bf67.4688394015275002309411.png);")
        self.img_underRegist.setText("")
        self.img_underRegist.setPixmap(QtGui.QPixmap(":/pins1/pergament2.png"))
        self.img_underRegist.setScaledContents(True)
        self.img_underRegist.setWordWrap(False)
        self.img_underRegist.setOpenExternalLinks(False)
        self.img_underRegist.setObjectName("img_underRegist")
        self.img_background.raise_()
        self.img_underRegist.raise_()
        self.formLayoutWidget.raise_()
        self.push_GoBack.raise_()
        self.label_Registration.raise_()
        self.push_AceptRegist.raise_()

        self.retranslateUi(RegistrationWidget)
        QtCore.QMetaObject.connectSlotsByName(RegistrationWidget)

    def retranslateUi(self, RegistrationWidget):
        _translate = QtCore.QCoreApplication.translate
        RegistrationWidget.setWindowTitle(_translate("RegistrationWidget", "Регистрация"))
        self.label_Name.setText(_translate("RegistrationWidget", "Логин  "))
        self.label_Password.setText(_translate("RegistrationWidget", "Пароль"))
        self.push_GoBack.setText(_translate("RegistrationWidget", "Отмена"))
        self.label_Registration.setText(_translate("RegistrationWidget", "Регистрация"))
        self.push_AceptRegist.setText(_translate("RegistrationWidget", "Зарегестрироваться"))
import images.resource1_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RegistrationWidget = QtWidgets.QWidget()
    ui = Ui_RegistrationWidget()
    ui.setupUi(RegistrationWidget)
    RegistrationWidget.show()
    sys.exit(app.exec_())
