# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Sovmestimosti_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SovmestimostiWidget(object):
    def setupUi(self, SovmestimostiWidget):
        SovmestimostiWidget.setObjectName("SovmestimostiWidget")
        SovmestimostiWidget.resize(400, 250)
        SovmestimostiWidget.setMinimumSize(QtCore.QSize(400, 250))
        SovmestimostiWidget.setMaximumSize(QtCore.QSize(400, 250))
        self.push_AceptAuthoriz = QtWidgets.QPushButton(SovmestimostiWidget)
        self.push_AceptAuthoriz.setGeometry(QtCore.QRect(10, 180, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(18)
        self.push_AceptAuthoriz.setFont(font)
        self.push_AceptAuthoriz.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0.0340909, stop:0 rgba(61, 61, 61, 255), stop:1 rgba(124, 124, 124, 255));\n"
"color: rgb(255, 253, 189)")
        self.push_AceptAuthoriz.setObjectName("push_AceptAuthoriz")
        self.push_GoBack = QtWidgets.QPushButton(SovmestimostiWidget)
        self.push_GoBack.setGeometry(QtCore.QRect(240, 180, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(16)
        self.push_GoBack.setFont(font)
        self.push_GoBack.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0.0340909, stop:0 rgba(61, 61, 61, 255), stop:1 rgba(124, 124, 124, 255));\n"
"color: rgb(255, 253, 189)")
        self.push_GoBack.setObjectName("push_GoBack")
        self.formLayoutWidget = QtWidgets.QWidget(SovmestimostiWidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(50, 70, 291, 81))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_Name = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        self.label_Name.setFont(font)
        self.label_Name.setStyleSheet("background-color: rgb(61, 61, 61);\n"
"color: rgb(255, 253, 189)")
        self.label_Name.setObjectName("label_Name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_Name)
        self.label_Password = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        self.label_Password.setFont(font)
        self.label_Password.setStyleSheet("background-color: rgb(61, 61, 61);\n"
"color: rgb(255, 253, 189)")
        self.label_Password.setObjectName("label_Password")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_Password)
        self.lineEdit_Password = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_Password.setFont(font)
        self.lineEdit_Password.setObjectName("lineEdit_Password")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Password)
        self.lineEdit_Name = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_Name.setFont(font)
        self.lineEdit_Name.setObjectName("lineEdit_Name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Name)
        self.label_Authorization = QtWidgets.QLabel(SovmestimostiWidget)
        self.label_Authorization.setGeometry(QtCore.QRect(100, 10, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(22)
        self.label_Authorization.setFont(font)
        self.label_Authorization.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"")
        self.label_Authorization.setObjectName("label_Authorization")
        self.img_underAuthoriz = QtWidgets.QLabel(SovmestimostiWidget)
        self.img_underAuthoriz.setGeometry(QtCore.QRect(60, 10, 261, 41))
        self.img_underAuthoriz.setStyleSheet("background-image: url(:/newPrefix/Downloads/kisspng-paper-scroll-parchment-clip-art-landscape-apge-with-pen-5b0bcdc6e5bf67.4688394015275002309411.png);")
        self.img_underAuthoriz.setText("")
        self.img_underAuthoriz.setPixmap(QtGui.QPixmap(":/newPrefix/Downloads/kisspng-paper-scroll-parchment-clip-art-landscape-apge-with-pen-5b0bcdc6e5bf67.4688394015275002309411.png"))
        self.img_underAuthoriz.setScaledContents(True)
        self.img_underAuthoriz.setObjectName("img_underAuthoriz")
        self.img_background = QtWidgets.QLabel(SovmestimostiWidget)
        self.img_background.setGeometry(QtCore.QRect(0, 0, 400, 250))
        self.img_background.setMinimumSize(QtCore.QSize(400, 250))
        self.img_background.setMaximumSize(QtCore.QSize(400, 250))
        self.img_background.setStyleSheet("background-image: url(:/newPrefix/Desktop/Прочее/uj7jKpEfRT4.jpg);")
        self.img_background.setText("")
        self.img_background.setPixmap(QtGui.QPixmap(":/newPrefix/Desktop/Прочее/uj7jKpEfRT4.jpg"))
        self.img_background.setScaledContents(True)
        self.img_background.setObjectName("img_background")
        self.label = QtWidgets.QLabel(SovmestimostiWidget)
        self.label.setGeometry(QtCore.QRect(80, 230, 241, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 0, 0);")
        self.label.setObjectName("label")
        self.img_background.raise_()
        self.img_underAuthoriz.raise_()
        self.push_AceptAuthoriz.raise_()
        self.push_GoBack.raise_()
        self.formLayoutWidget.raise_()
        self.label_Authorization.raise_()
        self.label.raise_()

        self.retranslateUi(SovmestimostiWidget)
        QtCore.QMetaObject.connectSlotsByName(SovmestimostiWidget)

    def retranslateUi(self, SovmestimostiWidget):
        _translate = QtCore.QCoreApplication.translate
        SovmestimostiWidget.setWindowTitle(_translate("SovmestimostiWidget", "Совместимость"))
        self.push_AceptAuthoriz.setText(_translate("SovmestimostiWidget", "Подтвердить!"))
        self.push_GoBack.setText(_translate("SovmestimostiWidget", "Я передумал..."))
        self.label_Name.setText(_translate("SovmestimostiWidget", " Раса "))
        self.label_Password.setText(_translate("SovmestimostiWidget", "Класс"))
        self.label_Authorization.setText(_translate("SovmestimostiWidget", "Совместимость"))
        self.label.setText(_translate("SovmestimostiWidget", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt;\">Писать Расы и Классы идентично табличным!</span></p></body></html>"))

import test_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SovmestimostiWidget = QtWidgets.QWidget()
    ui = Ui_SovmestimostiWidget()
    ui.setupUi(SovmestimostiWidget)
    SovmestimostiWidget.show()
    sys.exit(app.exec_())
